### ISSUE TITLE
There are some issues with the file 'enviromenents. yaml'

### ISSUE THREAD

**Issue by 1781950192** [alibaba-mmai-research/CLIP-FSAR#11]
**enviromenents. yaml， The environment here is incomplete**

### An error occurred while running this code：
python runs/run.py --cfg configs/projects/CLIPFSAR/ucf101/CLIPFSAR_UCF101_1shot_v1.yaml
/home/robot/anaconda3/envs/hyrsm/lib/python3.6/site-packages/aliyunsdkcore/auth/algorithm/sha_hmac256.py:20: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/robot/MyCode/CLIP-FSAR-master/models/base/few_shot.py:56: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
Loading config from /home/robot/MyCode/CLIP-FSAR-master/configs/projects/CLIPFSAR/ucf101/CLIPFSAR_UCF101_1shot_v1.yaml.

Traceback (most recent call last):
  File "/home/robot/MyCode/CLIP-FSAR-master/models/base/few_shot.py", line 325, in load
    model = torch.jit.load(opened_file, map_location=device if jit else "cpu").eval()
  File "/home/robot/anaconda3/envs/hyrsm/lib/python3.6/site-packages/torch/jit/__init__.py", line 230, in load
    cpp_module = torch._C.import_ir_module_from_buffer(cu, f.read(), map_location, _extra_files)
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1591914742272/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 4, but the maximum supported version for reading is 3. Your PyTorch installation may be too old.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runs/run.py", line 103, in <module>
    main()
  File "runs/run.py", line 97, in main
    launch_task(cfg=run[0], init_method=run[0].get_args().init_method, func=run[1])
  File "/home/robot/MyCode/CLIP-FSAR-master/utils/launcher.py", line 36, in launch_task
    func(cfg=cfg)
  File "/home/robot/MyCode/CLIP-FSAR-master/runs/train_net_few_shot.py", line 477, in train_few_shot
    model, model_ema = build_model(cfg)
  File "/home/robot/MyCode/CLIP-FSAR-master/models/base/builder.py", line 32, in build_model
    model = BaseVideoModel(cfg)
  File "/home/robot/MyCode/CLIP-FSAR-master/models/base/models.py", line 40, in __init__
    self.head = HEAD_REGISTRY.get(cfg.VIDEO.HEAD.NAME)(cfg=cfg)
  File "/home/robot/MyCode/CLIP-FSAR-master/models/base/few_shot.py", line 2700, in __init__
    backbone, self.preprocess = load(cfg.VIDEO.HEAD.BACKBONE_NAME, device="cuda", cfg=cfg, jit=False)   # ViT-B/16
  File "/home/robot/MyCode/CLIP-FSAR-master/models/base/few_shot.py", line 332, in load
    state_dict = torch.load(opened_file, map_location="cpu")
  File "/home/robot/anaconda3/envs/hyrsm/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/robot/anaconda3/envs/hyrsm/lib/python3.6/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by henry3556108** [comment]
I face the same issue.

**Comment by LiMo9687** [comment]
I also face the same issue, is there a solution?

**Comment by LiMo9687** [comment]
> I also face the same issue, is there a solution?

I tried to update my PyTorch version.
conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=10.2 -c pytorch

**Comment by aasasasaa** [comment]
@LiMo9687 hello  您好 请问您这种方式解决这个问题了吗 ？conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=10.2 -c pytorch  非常感谢您的回复！
